import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-theme="lemonade">
			<body className={`${inter.className} h-screen flex flex-col overflow-hidden`}>
				<header className="text-center text-2xl border-b-2 border-base-200 p-2">
					<h1 className="drop-shadow">
						<span className="text-secondary">Nutrient</span>
						<span className="text-primary">Tracker</span>
					</h1>
				</header>
				<main className="flex grow">{children}</main>
			</body>
		</html>
	);
}
